nav:
  - Home: index.md
  - In-kind Contributions: 
      - In-kind Contributions: in-kind/index.md
      - IDAC: in-kind/idac.md
      - Photo-z: in-kind/photoz.md
      - DESC Pipeline Scientists: in-kind/pipe-sci.md
  - Documents: docs.md
  - Contact: 'contact.md'


# Site information
site_name:  Documentação para Usuários
site_author: Julia Gschwend 
site_url: "http://bra-lin.linea.org.br"
repo_name: linea-it/bra-lin
repo_url: https://github.com/linea-it/bra-lin
edit_uri: 'edit/dev/docs'
use_directory_urls: false
copyright: 'Copyright &copy; 2006 - 2024 LIneA'
# cosmo, material-components, cerulean, journal, slate, readthedocs, readable, spacelab, united, bootstrap, simplex, flatly, yeti, psinder, amelia, cyborg, unidata, mkdocs


# Configuration
theme:
  name: material
  custom_dir: linea-theme
  logo: 'images/linea.png'
  favicon: 'images/linea_favicon.png'
  font:
    text: Roboto, Arial
  features:
    - navigation.indexes

  palette:
      # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
    primary: 'blue'
    accent: 'deep orange'

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
    primary: 'grey'
    accent: 'deep orange'

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: material/home-circle
      link: https://www.linea.org.br
    - icon: fontawesome/brands/github
      link: https://github.com/linea-it
    - icon: material/twitter
      link: https://twitter.com/linea_org
    - icon: material/instagram
      link: https://instagram.com/linea_org
    - icon: material/facebook
      link: https://facebook.com/linea.org
    - icon: material/youtube
      link: https://youtube.com/@linea_org

# Extensions
markdown_extensions:
  - attr_list
  - meta
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  
